apiVersion: v1
kind: Pod
metadata:
  name: pod-config-map
spec:
  containers:
  - name: app-v1
    image: hamdi06/app-v1-backend
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8089
    envFrom:
      - configMapRef:
          name: config-app
