apiVersion: v1
kind: ReplicationController
metadata:
  name: example-replication-controller
spec:
  replicas: 2
  selector:
    app: example-replication-controller
  template:
    metadata:
      name: example-replication-controller
      labels:
        app: example-replication-controller
        bahasa: ID
        type: BE
        lang: golang
    spec:
      containers:
        - name: example-replication-controller
          image: hamdi06/app-v1-backend
          ports:
            - containerPort: 8089
